CREATE SEQUENCE GROUP_EVENT_PK_SEQ START WITH 1 MAXVALUE 100000000;

CREATE TABLE GROUP_EVENT (
	GROUP_EVENT_ID INTEGER PRIMARY KEY NOT NULL,
	SHOW_ID VARCHAR(128) NOT NULL,
	CHANNEL_ID VARCHAR(128) NOT NULL,
	SHOW_TIME TIMESTAMP NOT NULL,
	MASTER_MDN VARCHAR(128) NOT NULL,
	CREATE_TIME TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL
);

CREATE INDEX IDX1_GROUP_EVENT ON GROUP_EVENT(SHOW_ID);

CREATE INDEX IDX2_GROUP_EVENT ON GROUP_EVENT(CHANNEL_ID);

CREATE INDEX IDX3_GROUP_EVENT ON GROUP_EVENT(SHOW_TIME);

CREATE INDEX IDX4_GROUP_EVENT ON GROUP_EVENT(MASTER_MDN);


CREATE TABLE GROUP_MEMBER (
	GROUP_EVENT_ID INTEGER NOT NULL,
	MDN VARCHAR(128) NOT NULL,
	MEMBER_STATUS VARCHAR(128) NOT NULL
);

ALTER TABLE GROUP_MEMBER ADD PRIMARY KEY (GROUP_EVENT_ID, MDN);

ALTER TABLE GROUP_MEMBER ADD CONSTRAINT FX1_GROUP_EVENT FOREIGN KEY (GROUP_EVENT_ID)
REFERENCES GROUP_EVENT(GROUP_EVENT_ID);

ALTER TABLE GROUP_MEMBER ADD CONSTRAINT CST1_GROUP_MEMBER
CHECK (MEMBER_STATUS IN ('MASTER', 'INVITED', 'ACCEPTED', 'DECLINED'));


